### PR TITLE
Some patches for 2005

### PR DESCRIPTION
**Pull request by jnothman**

### CODE REVIEW

**Comment by jnothman** [comment]
Also: from about february 2005 back the origxml is provided without whitespace, making diffs large. I may implement an XML tidying step in retrieval conditioned on date.

**Comment by henare** [comment]
@jnothman nice! :ok: Does this mean you've got all of 2005 to run through the parser?

**Comment by jnothman** [comment]
You're asking me to really brush off my ruby, huh?

**Comment by jnothman** [comment]
I'll try to contribute tests soon.

I *think* I ran all of 2005... this was a while ago :)

**Comment by henare** [comment]
>You're asking me to really brush off my ruby, huh?

If you look into it and it's too hard then let me know and I'll see what I can do :hammer_and_wrench: 

>I think I ran all of 2005... this was a while ago :)

It was a while ago :disappointed: sorry it took us so long to review it and thank you again so much for this contribution! :star2:

**Comment by jnothman** [comment]
> Also: from about february 2005 back the origxml is provided without whitespace, making diffs large. I may implement an XML tidying step in retrieval conditioned on date.

Is this worth doing?

**Comment by jnothman** [comment]
> Also: from about february 2005 back the origxml is provided without whitespace, making diffs large. I may implement an XML tidying step in retrieval conditioned on date.

Would I be correct in thinking that the same Hpricot rewrite used since 2011-05-10 would be appropriate (if I find the similar boundary date)?

**Comment by jnothman** [comment]
In terms of whether or not I've parsed all of 2005, I think I have, but I've not resolved data integration issues such as "Unknown speaker Ms JULIE BISHOP"

**Comment by henare** [comment]
>    Also: from about february 2005 back the origxml is provided without whitespace, making diffs large. I may implement an XML tidying step in retrieval conditioned on date.
>
>Is this worth doing?

From what I understand this would make parsing 2005 and earlier much easier. So the answer is definitely yes if we're going to do that :smile: It sounds like from your [later comment](https://github.com/openaustralia/openaustralia-parser/pull/17#issuecomment-325857764) that doing that parsing is a real possibility.

>Would I be correct in thinking that the same Hpricot rewrite used since 2011-05-10 would be appropriate (if I find the similar boundary date)?

I don't quite understand the question. Would using the same parser to parse 2005 as is used for data before 2011-05-10 be appropriate? Yes, I'd guess so and that's what will happen if we run the parser anyway.

I think we should move further discussion about parsing 2005 and earlier to its own issue and keep this discussion about this pull request :rocket:

**Comment by jnothman** [comment]
Okay.

**Comment by jnothman** [comment]
So I now recall that the only parser change here makes the storage of an element's `inner_text` conditional on that element's existence.

Now, I can't find much in the way of unit tests in the repository so far. Certainly not for bill cognate extraction. And the fix is obviously working in that it's not raising an error when `inner_text` is called, and that cognates are correctly extracted. But maybe you mean I should include an explicit assertion that another cognate exists with the same title, but having an `id.no` present.

I might have thought that the main testing of value here were non-regression tests: keep a set of orig/scraped pairs known to include particular issues, and make a test (ideally run by CI) of ensuring that their correspondence is maintained by all further changes. I think that's a separate issue, as is finding a set of exemplars to test those non-regressions and annotating the codepaths with IDs for the corresponding exemplars or vice-versa.

**Comment by henare** [comment]
@jnothman my idea with requesting tests was that something has been changed so let's test the changed behaviour. Are you saying that you don't think there's value in adding tests in this case?

**Comment by jnothman** [comment]
The change to the code is to allow it to work where a particular element is
missing. It should be easy to see from the code that no regression is
possible. The fact that it extends the current parser to cases where that
node does not exist. The test would be to show that days when this change
is needed get parsed fine.

**Comment by jnothman** [comment]
I think the confusion is merely that I looked for tests in test/ not
spec/... Excuse me.

**Comment by jnothman** [comment]
```
  it "should collect bills but ignore cognates whose ID is missing" do
``

Sorry, @henare, but I don't really think I can afford the effort to write a test in ruby, especially when I `HansardDay.bills` is currently untested.

**Comment by henare** [comment]
@jnothman fair enough :smiley:

**Comment by jnothman** [comment]
Sorry-- I didn't really intend this to be merged by attrition... I just
didn't get around to it.

**Pull request merged**
