### PR TITLE
updated the data of the ministers.csv file as per Issue # 612

### PR DESCRIPTION
**Pull request by has-taiar**
Sorry could not run the parser but I am submitting this PR as per @henare comment on https://github.com/openaustralia/openaustralia/issues/612

### CODE REVIEW

**Comment by henare** [comment]
Wow, we just came across this again. Sorry it fell through the cracks @has-taiar :cry: 

I'll assign this to me to keep it on my radar.

**Comment by henare** [comment]
Actually I'll assign it to @equivalentideas because he'd like to see if @micaelamicaela can help review this.

**Comment by MicaelaMicaela** [comment]
This has now been updated with the 24 Jan 2017 Turnbull ministry changes

**Comment by equivalentideas** [comment]
> Now up to date as of 24 Jan 2017 Turnbull Ministry

I've run this locally to confirm it runs. The changes look right to me 👍 Thanks @MicaelaMicaela and @has-taiar . Sorry this took so long @has-taiar This is a great contribution ❤️

**Pull request merged**
