### PR TITLE
Federal election 2016

### PR DESCRIPTION
**Pull request by henare**
This is the beginning of the work to update the data after the 2016 Federal Election.

These are the issues we need to cover:

* ~~https://github.com/openaustralia/openaustralia/issues/601~~
* ~~https://github.com/openaustralia/openaustralia/issues/594~~
* ~~Does anything need to happen due to electorate name changes?~~

Fixes https://github.com/openaustralia/openaustralia/issues/601
Fixes https://github.com/openaustralia/openaustralia/issues/594

### CODE REVIEW

**Comment by equivalentideas** [comment]
Here's a list of retiring MPs and Senators https://en.wikipedia.org/wiki/Australian_federal_election,_2016#Retiring_MPs_and_senators

**Comment by equivalentideas** [comment]
I’m going to start looking through the people changes to the Senate and updating as I go.

**Comment by henare** [comment]
I'll do the House of Representatives. This list looks handy: https://en.wikipedia.org/wiki/Australian_federal_election,_2016#Divisions_changing_hands

**Comment by equivalentideas** [comment]
Senate Twitter says that terms end on `9.5.2016` https://twitter.com/AuSenate/status/770484418792284160

**Comment by equivalentideas** [comment]
I've removed all the outgoing Senators ☝️

**Pull request merged**
