### PR TITLE
Slade Brockman has replaced Christopher Beck in the Senate

### PR DESCRIPTION
**Pull request by henare**
https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=30484

replaces

https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=J7Q

### CODE REVIEW

**Comment by henare** [comment]
Tested this using the [new Vagrant development setup](https://github.com/openaustralia/openaustralia/#development). Data looks good so I'm going to merge.

**Comment by jnothman** [comment]
Have you considered using WikiData queries to track changes in senate/reps (and even cabinet) composition? For instance http://tinyurl.com/ycxu93h8 will get the periods in which each Australian MP held their various positions.

**Comment by henare** [comment]
@jnothman that would be awesome. It's what EveryPolitician is doing too so it's probably the right way to go :+1:

**Comment by jnothman** [comment]
I was not aware of EveryPolitician. It's nice in an international
comparison context, though I don't know why they're capturing/reporting so
little in the biographical data. They are not, for instance, indicating
seniority (and do not even have prime ministership reported in their rich
JSON dump).

I have a larger query including all COAG legislatures, and reporting all
positions, party memberships and awards according to wikidata:
https://gist.github.com/jnothman/a60a7a906cd31cff8f9b0a5fa4012500. This is
what I thought might be useful to analyse politician data including
measures of seniority, changing affiliation, trajectory, etc. The
state-level data in Australia is not of great quality. Lots of MPs missing,
it seems. And I'm no SPARQL expert, so this may be a very poor way to query
for such data.

But even just running the federal positions query daily and posting the
diff to slack (or at least where it regards people with recent dates) would
enable timely manual updates.

**Comment by jnothman** [comment]
Note that one thing not consistently available is full names of people. To
automate things, you would need to add a mapping from Chris Back to
Christopher John Back, either in openaustralia or in wikidata.

**Comment by tmtmtmtm** [comment]
@jnothman at the moment EveryPolitician is only concerned with legislative positions, rather than executive ones (thus why the JSON doesn't mark who the Prime Minister is), however there's an `unstable/positions.csv` file that does include some basic information like this. That only really works at the minute in countries where cabinet-level positions require (or at least usually overlap) with also being a legislator. The wider goal, however, is to use Wikidata as the core datastore for all of this. There are certainly lots of gaps with the current Australian information in Wikidata, and we'd love to work together on helping resolve those (it's much better quality that most other countries thought!)

We already have a mapping between OpenAustralia IDs and Wikidata IDs: both of those are available in the `identifiers` section of anyone's record in EveryPolitician. It would be good to have properties for at least the APH identifiers, if not also the OpenAustralia ones in Wikidata, so that that doesn't need to be maintained out of band.

I'm not sure what you mean by "seniority" in this context: can you explain that a little more?

**Comment by jnothman** [comment]
Oh, I mean that in the context of data analysis, I'd like measures of how important/senior legislators are. Being members of cabinet is a simple one.

Data.openaustralia.org/members appears to be more reliable regarding executive (and parliamentary) roles than Wikidata ATM.

**Pull request merged**
